global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # StealthFlow Server
  - job_name: 'stealthflow-server'
    static_configs:
      - targets: ['stealthflow-server:9000']
    scrape_interval: 30s
    metrics_path: /metrics
    scheme: http

  # StealthFlow P2P Signaling
  - job_name: 'stealthflow-signaling'
    static_configs:
      - targets: ['stealthflow-signaling:8765']
    scrape_interval: 30s
    metrics_path: /metrics
    scheme: http
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter for system metrics (optional)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
