name: Bug Report
description: File a bug report to help us improve StealthFlow
title: "[Bug] "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.
        
        **SECURITY NOTICE**: Do not report security vulnerabilities here. Please see our [Security Policy](SECURITY.md) for responsible disclosure.

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checks
      description: Please verify these before submitting
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: This is not a security vulnerability (see SECURITY.md for reporting security issues)
          required: true
        - label: I have read the documentation and troubleshooting guide
          required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Client (GUI)
        - Client (CLI)  
        - Server
        - P2P System
        - Installation Script
        - Documentation
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: StealthFlow Version
      description: What version of StealthFlow are you running?
      placeholder: "e.g., 1.2.3"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What OS are you using?
      options:
        - Linux (Ubuntu/Debian)
        - Linux (CentOS/RHEL)
        - Linux (Other)
        - Windows 10/11
        - macOS
        - Docker Container
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Messages/Logs
      description: Please copy and paste any relevant error messages or log output
      render: text

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Relevant configuration details (remove sensitive information like passwords, domains, IPs)
      render: yaml

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Any additional environment details
      placeholder: |
        - Python version:
        - Network setup:
        - Firewall settings:
        - Other relevant software:

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here, including screenshots if helpful
